### ISSUE TITLE
Would using `performance.now()` instead of `Date.now()` increase accuracy?

### ISSUE THREAD

**Issue by deepsweet** [pirelenito/collect-fps#5]
* [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)
* [Can I use?](https://caniuse.com/#feat=high-resolution-time)

**Comment by xaviervia** [comment]
Technically, it would increase accuracy, but I don’t think it will do it at a resolution that we actually care about. The fastest refresh rate I could find from a google search is 240Hz, which is probably above what the eye can detect, and it still gives us a window of 4 milliseconds per frame, which means that even a 2 milliseconds inaccuracy will have no impact in the calculated FPS. And I would consider 240Hz a pretty extreme case. 

I don’t think we need greater resolution.

**Comment by xaviervia** [comment]
I love bikeshedding on this topic though.

**Comment by deepsweet** [comment]
>And I would consider 240Hz a pretty extreme case

Let's wait for 5 more years for crazy gaming requirements then.

**Comment by xaviervia** [comment]
More like, bionic eyes :D
